# Generated by Django 4.1 on 2024-02-02 16:14

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_alter_comment_create_date_alter_post_create_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="create_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="post",
            name="create_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 2, 2, 16, 14, 9, 614218, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
